In [141]:
import pandas as pd

In [142]:
df=pd.read_csv("titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [143]:
inputs=df.drop('Survived',axis='columns')

In [144]:
target=df["Survived"]

In [145]:
from sklearn.preprocessing import LabelEncoder
le_sex = LabelEncoder()

In [146]:
inputs['Sex_n'] = le_sex.fit_transform(inputs['Sex'])
inputs.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_n
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1

In [147]:
inputs_n = inputs.drop(['Sex'], axis='columns')

In [148]:
inputs_n.head()

,PassengerId,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_n
0,1,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,S,0
4,5,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,S,1

In [149]:
inputs_n = inputs[['Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex_n']].copy()
# Fill missing 'Age' values with the mean
inputs_n['Age'].fillna(inputs_n['Age'].mean(), inplace=True)
inputs_n

/tmp/ipykernel_764/4063478027.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  inputs_n['Age'].fillna(inputs_n['Age'].mean(), inplace=True)

     Pclass        Age  SibSp  Parch     Fare  Sex_n
0         3  22.000000      1      0   7.2500      1
1         1  38.000000      1      0  71.2833      0
2         3  26.000000      0      0   7.9250      0
3         1  35.000000      1      0  53.1000      0
4         3  35.000000      0      0   8.0500      1
..      ...        ...    ...    ...      ...    ...
886       2  27.000000      0      0  13.0000      1
887       1  19.000000      0      0  30.0000      0
888       3  29.699118      1      2  23.4500      0
889       1  26.000000      0      0  30.0000      1
890       3  32.000000      0      0   7.7500      1

[891 rows x 6 columns]

In [150]:
target

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [151]:
from sklearn import tree

In [152]:
model = tree.DecisionTreeClassifier()
model.fit(inputs_n, target)

DecisionTreeClassifier()

In [153]:

model.score(inputs_n, target)

0.9820426487093153