In [10]:
import pandas as pd
df = pd.read_csv("one_hot_encoding.csv")
df

                Car Model  Mileage  Age(yrs)  Sell Price($)
0                  BMW X5    69000         6          18000
1                  BMW X5    35000         3          34000
2                  BMW X5    57000         5          26100
3                  BMW X5    22500         2          40000
4                  BMW X5    46000         4          31500
5                 Audi A5    59000         5          29400
6                 Audi A5    52000         5          32000
7                 Audi A5    72000         6          19300
8                 Audi A5    91000         8          12000
9                 Audi A5    67000         6          22000
10  Mercedez Benz C class    83000         7          20000
11  Mercedez Benz C class    79000         7          21000
12  Mercedez Benz C class    59000         5          33000
13  Mercedez Benz C class    58780         4          27500
14  Mercedez Benz C class    82450         7          19400
15  Mercedez Benz C class    25400         3          40500

In [24]:
dummies = pd.get_dummies(df['Car Model'])

print(dummies)

    Audi A5  BMW X5  Mercedez Benz C class
0     False    True                  False
1     False    True                  False
2     False    True                  False
3     False    True                  False
4     False    True                  False
5      True   False                  False
6      True   False                  False
7      True   False                  False
8      True   False                  False
9      True   False                  False
10    False   False                   True
11    False   False                   True
12    False   False                   True
13    False   False                   True
14    False   False                   True
15    False   False                   True

In [25]:
merged = pd.concat([df,dummies],axis='columns')
merged

,Car Model,Mileage,Age(yrs),Sell Price($),Audi A5,BMW X5,Mercedez Benz C class
0,BMW X5,69000,6,18000,False,True,False
1,BMW X5,35000,3,34000,False,True,False
2,BMW X5,57000,5,26100,False,True,False
3,BMW X5,22500,2,40000,False,True,False
4,BMW X5,46000,4,31500,False,True,False
5,Audi A5,59000,5,29400,True,False,False
6,Audi A5,52000,5,32000,True,False,False
7,Audi A5,72000,6,19300,True,False,False
8,Audi A5,91000,8,12000,True,False,False
9,Audi A5,67000,6,22000,True,False,False
10,Mercedez Benz C class,83000,7,20000,False,False,True
11,Mercedez Benz C class,79000,7,21000,False,False,True
12,Mercedez Benz C class,59000,5,33000,False,False,True
13,Mercedez Benz C class,58780,4,27500,False,False,True
14,Mercedez Benz C class,82450,7,19400,False,False,True
15,Mercedez Benz C class,25400,3,40500,False,False,True

In [26]:
final = merged.drop(['Car Model'], axis='columns')
final

    Mileage  Age(yrs)  Sell Price($)  Audi A5  BMW X5  Mercedez Benz C class
0     69000         6          18000    False    True                  False
1     35000         3          34000    False    True                  False
2     57000         5          26100    False    True                  False
3     22500         2          40000    False    True                  False
4     46000         4          31500    False    True                  False
5     59000         5          29400     True   False                  False
6     52000         5          32000     True   False                  False
7     72000         6          19300     True   False                  False
8     91000         8          12000     True   False                  False
9     67000         6          22000     True   False                  False
10    83000         7          20000    False   False                   True
11    79000         7          21000    False   False                   True
12    59000         5          33000    False   False                   True
13    58780         4          27500    False   False                   True
14    82450         7          19400    False   False                   True
15    25400         3          40500    False   False                   True

In [30]:
final = final.drop(['Mercedez Benz C class'], axis='columns')
final

    Mileage  Age(yrs)  Sell Price($)  Audi A5  BMW X5
0     69000         6          18000    False    True
1     35000         3          34000    False    True
2     57000         5          26100    False    True
3     22500         2          40000    False    True
4     46000         4          31500    False    True
5     59000         5          29400     True   False
6     52000         5          32000     True   False
7     72000         6          19300     True   False
8     91000         8          12000     True   False
9     67000         6          22000     True   False
10    83000         7          20000    False   False
11    79000         7          21000    False   False
12    59000         5          33000    False   False
13    58780         4          27500    False   False
14    82450         7          19400    False   False
15    25400         3          40500    False   False

In [36]:
X = final.drop('Sell Price($)', axis='columns')
X

    Mileage  Age(yrs)  Audi A5  BMW X5
0     69000         6    False    True
1     35000         3    False    True
2     57000         5    False    True
3     22500         2    False    True
4     46000         4    False    True
5     59000         5     True   False
6     52000         5     True   False
7     72000         6     True   False
8     91000         8     True   False
9     67000         6     True   False
10    83000         7    False   False
11    79000         7    False   False
12    59000         5    False   False
13    58780         4    False   False
14    82450         7    False   False
15    25400         3    False   False

In [40]:
y = final['Sell Price($)']

In [41]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [42]:
model.fit(X,y)

LinearRegression()

In [43]:
model.predict(X)

array([20113.37848985, 34548.608634  , 25206.86763644, 39853.40710449,
       29877.73813522, 26850.15693272, 29808.48746739, 21334.04913832,
       13260.1640842 , 23447.14237737, 19092.83191423, 20783.30650547,
       29279.81020741, 29394.85168279, 19325.27217053, 43523.92751957])

In [44]:
model.score(X,y)

0.9462236292879906

In [45]:
model.predict([[0,0,45000,4]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([-1.09299745e+08])

In [46]:
# 2) Predict price of BMW X5
model.predict([[1,0,86000,7]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([-2.08930285e+08])

In [47]:
# 3) Model accuracy score
model.score(X,y)

0.9462236292879906